version: 2
updates:
    - package-ecosystem: "maven"
      directory: "/"
      schedule:
        interval: "monthly"
      open-pull-requests-limit: 5
      commit-message:
        prefix: "fix(deps)"
      labels:
        - "dependencies"
        - "java"
      groups:
        libraries:
          patterns:
            - "org.apache.commons:commons-lang3"
            - "org.apache.commons:commons-collections4"

        spring:
            patterns:
                - "org.springframework.boot:spring-boot-*"
                - "org.springframework:spring-*"
        testing:
            patterns:
                - "org.junit*"
                - "org.mockito*"

      ignore:
        - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
          versions: ["3.5.x"]



    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "monthly"
      labels:
        - "dependencies"
        - "github-actions"