apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: default
  labels:
    app: catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: catalog-service
          image: 287238298856.dkr.ecr.eu-north-1.amazonaws.com/catalog-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: staging
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          volumeMounts:
            - name: app-config
              mountPath: /app/config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: app-config
          configMap:
            name: catalog-service-config