apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  DB_HOST: amRiYzpwb3N0Z3Jlc3FsOi8vY2F0YWxvZy1zZXJ2aWNlLWRhdGFiYXNlLmNka3Uwbzg2a245di5ldS1ub3J0aC0xLnJkcy5hbWF6b25hd3MuY29tL2NhdGFsb2dfZGI=
  DB_USERNAME: eGNoYW4=
  DB_PASSWORD: U3RhbmRhcmQ5MA==