name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches: ['**']
    paths:
      - '*/src/*'
      - '.github/workflows/**.yml'
  push:
    branches: ['**']
    paths:
      - '*/src/*'
      - '.github/workflows/**.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn -B test

      - name: Package application
        run: mvn -B package -DskipTests