name: Build and Deploy to AWS ECR
on:
  push:
    branches:
      - main
    paths:
      - '**/src/**'
      - '.github/workflows/**.yml'

env:
    AWS_REGION: us-east-1
    ECR_REPOSITORY: your-ecr-repository-name
    IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn -B test

      - name: Package application
        run: mvn -B package -DskipTests

      - name: Build Docker image
        run: docker build -t ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .

      - name: Log in to Amazon ECR
      - uses: aws-actions/amazon-ecr-login@v1
#        with:
#          region: ${{ env.AWS_REGION }}
#          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Push Docker image to ECR
        run: |
          docker tag ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} ${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
